use glam::vec3;

use crate::{
    plot::model::{MotionKind, MotionSegment, ToolSettings, ToolpathPlan, ToolpathStats},
    svg::toolpath::PreparedSvg,
};

pub fn build_plan(prepared: PreparedSvg, settings: &ToolSettings) -> ToolpathPlan {
    let mut segments = Vec::new();
    let mut segment_end_times_s = Vec::new();
    let mut gcode_lines = Vec::new();

    let draw_feed = settings.print_feed_rate();
    let travel_feed = settings.travel_feed_rate();
    let draw_speed = (draw_feed / 60.0).max(1.0);
    let travel_speed = (travel_feed / 60.0).max(1.0);
    let lift = settings.lift_height_mm;

    gcode_lines.push("; Generated by Penartic".to_owned());
    gcode_lines.push(format!("; Source: {}", prepared.source_name));
    gcode_lines.push("G21".to_owned());
    gcode_lines.push("G90".to_owned());

    let mut current = vec3(0.0, 0.0, 0.0);
    let lifted_origin = vec3(0.0, 0.0, lift);
    push_relative_z_motion_if_needed(
        &mut segments,
        &mut segment_end_times_s,
        &mut gcode_lines,
        &mut current,
        lifted_origin,
        travel_speed,
        travel_feed,
    );

    gcode_lines.push("G28 X Y".to_owned());
    current = lifted_origin;

    let mut stroke_count = 0;
    let mut active_feed_rate = None;

    for polyline in prepared.polylines.iter().filter(|polyline| polyline.len() >= 2) {
        stroke_count += 1;

        let start = vec3(polyline[0].x, polyline[0].y, lift);
        if current.distance_squared(start) > 1e-6 {
            push_segment(
                &mut segments,
                &mut segment_end_times_s,
                current,
                start,
                MotionKind::Travel,
                travel_speed,
            );
            push_g1_move(
                &mut gcode_lines,
                &mut active_feed_rate,
                travel_feed,
                Some(start.x),
                Some(start.y),
                None,
            );
            current = start;
        }

        let lowered = vec3(start.x, start.y, 0.0);
        push_relative_z_motion_if_needed(
            &mut segments,
            &mut segment_end_times_s,
            &mut gcode_lines,
            &mut current,
            lowered,
            travel_speed,
            travel_feed,
        );
        active_feed_rate = None;

        for point in polyline.iter().skip(1) {
            let next = vec3(point.x, point.y, 0.0);
            if current.distance_squared(next) <= 1e-6 {
                continue;
            }

            push_segment(
                &mut segments,
                &mut segment_end_times_s,
                current,
                next,
                MotionKind::Draw,
                draw_speed,
            );
            push_g1_move(
                &mut gcode_lines,
                &mut active_feed_rate,
                draw_feed,
                Some(next.x),
                Some(next.y),
                None,
            );
            current = next;
        }

        let raised = vec3(current.x, current.y, lift);
        push_relative_z_motion_if_needed(
            &mut segments,
            &mut segment_end_times_s,
            &mut gcode_lines,
            &mut current,
            raised,
            travel_speed,
            travel_feed,
        );
        active_feed_rate = None;
    }

    gcode_lines.push("M400".to_owned());

    let mut stats =
        ToolpathStats { stroke_count, segment_count: segments.len(), ..Default::default() };

    for segment in &segments {
        match segment.kind {
            MotionKind::Travel => {
                stats.travel_distance_mm += segment.length();
                stats.estimated_duration_s += segment.duration_s;
            }
            MotionKind::Draw => {
                stats.drawing_distance_mm += segment.length();
                stats.estimated_duration_s += segment.duration_s;
            }
        }
    }

    ToolpathPlan {
        source_name: prepared.source_name,
        printable_area: settings.printable_area,
        drawing_origin: prepared.drawing_origin,
        drawing_bounds: prepared.drawing_bounds,
        is_out_of_bounds: prepared.is_out_of_bounds,
        segments,
        segment_end_times_s,
        gcode_lines,
        warnings: prepared.warnings,
        stats,
    }
}

fn push_relative_z_motion_if_needed(
    segments: &mut Vec<MotionSegment>,
    segment_end_times_s: &mut Vec<f32>,
    gcode_lines: &mut Vec<String>,
    current: &mut glam::Vec3,
    end: glam::Vec3,
    speed_mm_s: f32,
    feed_rate_mm_min: f32,
) {
    if current.distance_squared(end) <= 1e-6 {
        return;
    }

    debug_assert!((current.x - end.x).abs() <= 1e-6);
    debug_assert!((current.y - end.y).abs() <= 1e-6);

    push_segment(segments, segment_end_times_s, *current, end, MotionKind::Travel, speed_mm_s);
    gcode_lines.push("G91".to_owned());
    gcode_lines.push(format!("G1 Z{:.3} F{:.0}", end.z - current.z, feed_rate_mm_min.round()));
    gcode_lines.push("G90".to_owned());
    *current = end;
}

fn push_g1_move(
    gcode_lines: &mut Vec<String>,
    active_feed_rate: &mut Option<i32>,
    feed_rate_mm_min: f32,
    x: Option<f32>,
    y: Option<f32>,
    z: Option<f32>,
) {
    let mut line = "G1".to_owned();

    if let Some(x) = x {
        line.push_str(&format!(" X{x:.2}"));
    }
    if let Some(y) = y {
        line.push_str(&format!(" Y{y:.2}"));
    }
    if let Some(z) = z {
        line.push_str(&format!(" Z{z:.3}"));
    }

    let rounded_feed_rate = feed_rate_mm_min.round() as i32;
    if active_feed_rate.is_none_or(|active| active != rounded_feed_rate) {
        line.push_str(&format!(" F{rounded_feed_rate}"));
        *active_feed_rate = Some(rounded_feed_rate);
    }

    gcode_lines.push(line);
}

fn push_segment(
    segments: &mut Vec<MotionSegment>,
    segment_end_times_s: &mut Vec<f32>,
    start: glam::Vec3,
    end: glam::Vec3,
    kind: MotionKind,
    speed_mm_s: f32,
) {
    let duration_s = start.distance(end) / speed_mm_s.max(1e-3);
    segments.push(MotionSegment { start, end, kind, duration_s });
    let cumulative_s = segment_end_times_s.last().copied().unwrap_or(0.0) + duration_s;
    segment_end_times_s.push(cumulative_s);
}

#[cfg(test)]
mod tests {
    use glam::vec2;

    use super::*;
    use crate::plot::model::{PrintableArea, ToolSettings};
    use crate::svg::toolpath::PreparedSvg;

    #[test]
    fn generated_gcode_lifts_then_homes_xy() {
        let prepared = PreparedSvg {
            source_name: "shape.svg".to_owned(),
            polylines: vec![vec![vec2(10.0, 10.0), vec2(40.0, 10.0)]],
            warnings: Vec::new(),
            drawing_origin: vec2(10.0, 10.0),
            drawing_bounds: vec2(30.0, 0.0),
            is_out_of_bounds: false,
        };

        let plan = build_plan(
            prepared,
            &ToolSettings {
                printable_area: PrintableArea::new(100.0, 100.0),
                print_speed_mm_s: 25.0,
                lift_height_mm: 2.0,
            },
        );

        assert_eq!(plan.gcode_lines[2], "G21");
        assert_eq!(plan.gcode_lines[3], "G90");
        assert_eq!(plan.gcode_lines[4], "G91");
        assert_eq!(plan.gcode_lines[5], "G1 Z2.000 F3000");
        assert_eq!(plan.gcode_lines[6], "G90");
        assert_eq!(plan.gcode_lines[7], "G28 X Y");
        assert_eq!(plan.gcode_lines[8], "G1 X10.00 Y10.00 F3000");
        assert_eq!(plan.gcode_lines[9], "G91");
        assert_eq!(plan.gcode_lines[10], "G1 Z-2.000 F3000");
        assert_eq!(plan.gcode_lines[11], "G90");
        assert_eq!(plan.gcode_lines[12], "G1 X40.00 Y10.00 F1500");
    }

    #[test]
    fn omits_redundant_feed_rate_from_consecutive_draw_moves() {
        let prepared = PreparedSvg {
            source_name: "shape.svg".to_owned(),
            polylines: vec![vec![vec2(0.0, 0.0), vec2(10.0, 0.0), vec2(20.0, 0.0)]],
            warnings: Vec::new(),
            drawing_origin: vec2(0.0, 0.0),
            drawing_bounds: vec2(20.0, 0.0),
            is_out_of_bounds: false,
        };

        let plan = build_plan(prepared, &ToolSettings::default());
        let draw_lines = plan
            .gcode_lines
            .iter()
            .filter(|line| line.starts_with("G1 X"))
            .cloned()
            .collect::<Vec<_>>();

        assert!(draw_lines.iter().any(|line| line.contains(" F")));
        assert!(draw_lines.iter().any(|line| !line.contains(" F")));
    }
}
