use glam::vec3;

use crate::{
    plot::model::{
        CurveOutputMode, MotionKind, MotionSegment, PrintStartMode, ToolSettings, ToolpathPlan,
        ToolpathStats,
    },
    svg::{
        ir::{CubicBezierSegment, SvgIrSegment},
        toolpath::PreparedSvg,
    },
};

pub fn build_plan(prepared: PreparedSvg, settings: &ToolSettings) -> ToolpathPlan {
    let mut segments = Vec::new();
    let mut segment_end_times_s = Vec::new();
    let mut gcode_lines = Vec::new();

    let draw_feed = settings.print_feed_rate();
    let travel_feed = settings.travel_feed_rate();
    let draw_speed = (draw_feed / 60.0).max(1.0);
    let travel_speed = (travel_feed / 60.0).max(1.0);
    let lift = settings.lift_height_mm;
    let first_draw_point = prepared.strokes.iter().find_map(|stroke| stroke.start_point());

    gcode_lines.push("; Generated by Penartic".to_owned());
    gcode_lines.push(format!("; Source: {}", prepared.source_name));
    gcode_lines.push("G21".to_owned());
    gcode_lines.push("G90".to_owned());

    let mut current = match settings.print_start_mode {
        PrintStartMode::HomeBeforePrint => {
            let mut current = vec3(0.0, 0.0, 0.0);
            let lifted_origin = vec3(0.0, 0.0, lift);
            push_relative_z_motion_if_needed(
                &mut segments,
                &mut segment_end_times_s,
                &mut gcode_lines,
                &mut current,
                lifted_origin,
                travel_speed,
                travel_feed,
            );

            gcode_lines.push("G28 X Y".to_owned());
            lifted_origin
        }
        PrintStartMode::DirectFromCurrentPosition => first_draw_point
            .map(|point| vec3(point.x, point.y, 0.0))
            .unwrap_or_else(|| vec3(0.0, 0.0, 0.0)),
    };

    let mut stroke_count = 0;
    let mut active_feed_rate = None;
    let mut is_first_stroke = true;

    for stroke in prepared.strokes.iter().filter(|stroke| !stroke.is_empty()) {
        stroke_count += 1;

        let start_draw = stroke.start_point().map(|point| vec3(point.x, point.y, 0.0)).unwrap();
        if settings.print_start_mode == PrintStartMode::HomeBeforePrint || !is_first_stroke {
            push_position_to_stroke_start(
                &mut segments,
                &mut segment_end_times_s,
                &mut gcode_lines,
                &mut current,
                start_draw,
                lift,
                travel_speed,
                travel_feed,
                &mut active_feed_rate,
            );
        } else {
            debug_assert!(current.distance_squared(start_draw) <= 1e-6);
            current = start_draw;
        }

        for ir_segment in &stroke.segments {
            append_draw_segment(
                &mut segments,
                &mut segment_end_times_s,
                &mut gcode_lines,
                &mut current,
                *ir_segment,
                settings.curve_output_mode,
                draw_speed,
                draw_feed,
                &mut active_feed_rate,
            );
        }

        let raised = vec3(current.x, current.y, lift);
        push_relative_z_motion_if_needed(
            &mut segments,
            &mut segment_end_times_s,
            &mut gcode_lines,
            &mut current,
            raised,
            travel_speed,
            travel_feed,
        );
        active_feed_rate = None;
        is_first_stroke = false;
    }

    gcode_lines.push("M400".to_owned());

    let mut stats =
        ToolpathStats { stroke_count, segment_count: segments.len(), ..Default::default() };

    for segment in &segments {
        match segment.kind {
            MotionKind::Travel => {
                stats.travel_distance_mm += segment.length();
                stats.estimated_duration_s += segment.duration_s;
            }
            MotionKind::Draw => {
                stats.drawing_distance_mm += segment.length();
                stats.estimated_duration_s += segment.duration_s;
            }
        }
    }

    let mut warnings = prepared.warnings;
    if settings.curve_output_mode == CurveOutputMode::PreferG5
        && prepared
            .strokes
            .iter()
            .flat_map(|stroke| stroke.segments.iter())
            .any(|segment| matches!(segment, SvgIrSegment::Quadratic(_) | SvgIrSegment::Cubic(_)))
    {
        warnings.push(
            "G5 곡선 출력은 지원 펌웨어에서만 올바르게 동작합니다. 지원하지 않으면 선분 출력 모드를 사용하세요."
                .to_owned(),
        );
    }

    ToolpathPlan {
        source_name: prepared.source_name,
        printable_area: settings.printable_area,
        drawing_origin: prepared.drawing_origin,
        drawing_bounds: prepared.drawing_bounds,
        first_draw_point,
        is_out_of_bounds: prepared.is_out_of_bounds,
        segments,
        segment_end_times_s,
        gcode_lines,
        warnings,
        stats,
    }
}

fn append_draw_segment(
    segments: &mut Vec<MotionSegment>,
    segment_end_times_s: &mut Vec<f32>,
    gcode_lines: &mut Vec<String>,
    current: &mut glam::Vec3,
    ir_segment: SvgIrSegment,
    curve_output_mode: CurveOutputMode,
    draw_speed: f32,
    draw_feed: f32,
    active_feed_rate: &mut Option<i32>,
) {
    let points = ir_segment.flatten_points();
    for window in points.windows(2) {
        let next = vec3(window[1].x, window[1].y, 0.0);
        if current.distance_squared(next) <= 1e-6 {
            continue;
        }
        push_segment(segments, segment_end_times_s, *current, next, MotionKind::Draw, draw_speed);
        *current = next;
    }

    if curve_output_mode == CurveOutputMode::PreferG5 {
        if let Some(cubic) = ir_segment.to_cubic_bezier() {
            push_g5_move(gcode_lines, active_feed_rate, draw_feed, cubic);
            return;
        }
    }

    for point in points.into_iter().skip(1) {
        push_g1_move(gcode_lines, active_feed_rate, draw_feed, Some(point.x), Some(point.y), None);
    }
}

fn push_position_to_stroke_start(
    segments: &mut Vec<MotionSegment>,
    segment_end_times_s: &mut Vec<f32>,
    gcode_lines: &mut Vec<String>,
    current: &mut glam::Vec3,
    start_draw: glam::Vec3,
    lift: f32,
    travel_speed: f32,
    travel_feed: f32,
    active_feed_rate: &mut Option<i32>,
) {
    let lifted_current = vec3(current.x, current.y, lift);
    push_relative_z_motion_if_needed(
        segments,
        segment_end_times_s,
        gcode_lines,
        current,
        lifted_current,
        travel_speed,
        travel_feed,
    );

    let start_lifted = vec3(start_draw.x, start_draw.y, lift);
    if current.distance_squared(start_lifted) > 1e-6 {
        push_segment(
            segments,
            segment_end_times_s,
            *current,
            start_lifted,
            MotionKind::Travel,
            travel_speed,
        );
        push_g1_move(
            gcode_lines,
            active_feed_rate,
            travel_feed,
            Some(start_lifted.x),
            Some(start_lifted.y),
            None,
        );
        *current = start_lifted;
    }

    push_relative_z_motion_if_needed(
        segments,
        segment_end_times_s,
        gcode_lines,
        current,
        start_draw,
        travel_speed,
        travel_feed,
    );
    *active_feed_rate = None;
}

fn push_relative_z_motion_if_needed(
    segments: &mut Vec<MotionSegment>,
    segment_end_times_s: &mut Vec<f32>,
    gcode_lines: &mut Vec<String>,
    current: &mut glam::Vec3,
    end: glam::Vec3,
    speed_mm_s: f32,
    feed_rate_mm_min: f32,
) {
    if current.distance_squared(end) <= 1e-6 {
        return;
    }

    debug_assert!((current.x - end.x).abs() <= 1e-6);
    debug_assert!((current.y - end.y).abs() <= 1e-6);

    push_segment(segments, segment_end_times_s, *current, end, MotionKind::Travel, speed_mm_s);
    gcode_lines.push("G91".to_owned());
    gcode_lines.push(format!("G1 Z{:.3} F{:.0}", end.z - current.z, feed_rate_mm_min.round()));
    gcode_lines.push("G90".to_owned());
    *current = end;
}

fn push_g1_move(
    gcode_lines: &mut Vec<String>,
    active_feed_rate: &mut Option<i32>,
    feed_rate_mm_min: f32,
    x: Option<f32>,
    y: Option<f32>,
    z: Option<f32>,
) {
    let mut line = "G1".to_owned();

    if let Some(x) = x {
        line.push_str(&format!(" X{x:.2}"));
    }
    if let Some(y) = y {
        line.push_str(&format!(" Y{y:.2}"));
    }
    if let Some(z) = z {
        line.push_str(&format!(" Z{z:.3}"));
    }

    let rounded_feed_rate = feed_rate_mm_min.round() as i32;
    if active_feed_rate.is_none_or(|active| active != rounded_feed_rate) {
        line.push_str(&format!(" F{rounded_feed_rate}"));
        *active_feed_rate = Some(rounded_feed_rate);
    }

    gcode_lines.push(line);
}

fn push_g5_move(
    gcode_lines: &mut Vec<String>,
    active_feed_rate: &mut Option<i32>,
    feed_rate_mm_min: f32,
    cubic: CubicBezierSegment,
) {
    let mut line = format!(
        "G5 I{:.3} J{:.3} P{:.3} Q{:.3} X{:.2} Y{:.2}",
        cubic.control_a.x - cubic.start.x,
        cubic.control_a.y - cubic.start.y,
        cubic.control_b.x - cubic.end.x,
        cubic.control_b.y - cubic.end.y,
        cubic.end.x,
        cubic.end.y,
    );

    let rounded_feed_rate = feed_rate_mm_min.round() as i32;
    if active_feed_rate.is_none_or(|active| active != rounded_feed_rate) {
        line.push_str(&format!(" F{rounded_feed_rate}"));
        *active_feed_rate = Some(rounded_feed_rate);
    }

    gcode_lines.push(line);
}

fn push_segment(
    segments: &mut Vec<MotionSegment>,
    segment_end_times_s: &mut Vec<f32>,
    start: glam::Vec3,
    end: glam::Vec3,
    kind: MotionKind,
    speed_mm_s: f32,
) {
    let duration_s = start.distance(end) / speed_mm_s.max(1e-3);
    segments.push(MotionSegment { start, end, kind, duration_s });
    let cumulative_s = segment_end_times_s.last().copied().unwrap_or(0.0) + duration_s;
    segment_end_times_s.push(cumulative_s);
}

#[cfg(test)]
mod tests {
    use glam::vec2;

    use super::*;
    use crate::{
        plot::model::{CurveOutputMode, PrintStartMode, PrintableArea, ToolSettings},
        svg::{
            ir::{QuadraticBezierSegment, SvgIrStroke},
            toolpath::PreparedSvg,
        },
    };

    fn line_prepared_svg() -> PreparedSvg {
        PreparedSvg {
            source_name: "shape.svg".to_owned(),
            strokes: vec![SvgIrStroke::new(vec![SvgIrSegment::line(
                vec2(10.0, 10.0),
                vec2(40.0, 10.0),
            )])],
            warnings: Vec::new(),
            drawing_origin: vec2(10.0, 10.0),
            drawing_bounds: vec2(30.0, 0.0),
            is_out_of_bounds: false,
        }
    }

    #[test]
    fn generated_gcode_lifts_then_homes_xy() {
        let plan = build_plan(
            line_prepared_svg(),
            &ToolSettings {
                printable_area: PrintableArea::new(100.0, 100.0),
                print_speed_mm_s: 25.0,
                lift_height_mm: 2.0,
                print_start_mode: PrintStartMode::HomeBeforePrint,
                curve_output_mode: CurveOutputMode::LinearSegments,
            },
        );

        assert_eq!(plan.gcode_lines[2], "G21");
        assert_eq!(plan.gcode_lines[3], "G90");
        assert_eq!(plan.gcode_lines[4], "G91");
        assert_eq!(plan.gcode_lines[5], "G1 Z2.000 F3000");
        assert_eq!(plan.gcode_lines[6], "G90");
        assert_eq!(plan.gcode_lines[7], "G28 X Y");
        assert_eq!(plan.gcode_lines[8], "G1 X10.00 Y10.00 F3000");
        assert_eq!(plan.gcode_lines[9], "G91");
        assert_eq!(plan.gcode_lines[10], "G1 Z-2.000 F3000");
        assert_eq!(plan.gcode_lines[11], "G90");
        assert_eq!(plan.gcode_lines[12], "G1 X40.00 Y10.00 F1500");
        assert_eq!(plan.first_draw_point, Some(vec2(10.0, 10.0)));
    }

    #[test]
    fn direct_start_skips_initial_home_and_z_motion() {
        let plan = build_plan(
            line_prepared_svg(),
            &ToolSettings {
                printable_area: PrintableArea::new(100.0, 100.0),
                print_speed_mm_s: 25.0,
                lift_height_mm: 2.0,
                print_start_mode: PrintStartMode::DirectFromCurrentPosition,
                curve_output_mode: CurveOutputMode::LinearSegments,
            },
        );

        assert_eq!(plan.gcode_lines[2], "G21");
        assert_eq!(plan.gcode_lines[3], "G90");
        assert_eq!(plan.gcode_lines[4], "G1 X40.00 Y10.00 F1500");
        assert!(!plan.gcode_lines.iter().any(|line| line == "G28 X Y"));
        assert!(!plan.gcode_lines[..5].iter().any(|line| line.starts_with("G1 Z")));
        assert!(matches!(
            plan.segments.first().map(|segment| segment.kind),
            Some(MotionKind::Draw)
        ));
    }

    #[test]
    fn emits_g5_for_curve_segments_when_enabled() {
        let prepared = PreparedSvg {
            source_name: "curve.svg".to_owned(),
            strokes: vec![SvgIrStroke::new(vec![SvgIrSegment::Quadratic(
                QuadraticBezierSegment {
                    start: vec2(0.0, 0.0),
                    control: vec2(5.0, 10.0),
                    end: vec2(10.0, 0.0),
                },
            )])],
            warnings: Vec::new(),
            drawing_origin: vec2(0.0, 0.0),
            drawing_bounds: vec2(10.0, 10.0),
            is_out_of_bounds: false,
        };

        let plan = build_plan(
            prepared,
            &ToolSettings {
                printable_area: PrintableArea::new(100.0, 100.0),
                print_speed_mm_s: 25.0,
                lift_height_mm: 2.0,
                print_start_mode: PrintStartMode::DirectFromCurrentPosition,
                curve_output_mode: CurveOutputMode::PreferG5,
            },
        );

        assert!(plan.gcode_lines.iter().any(|line| line.starts_with("G5 ")));
        assert!(plan.warnings.iter().any(|warning| warning.contains("G5")));
    }

    #[test]
    fn omits_redundant_feed_rate_from_consecutive_draw_moves() {
        let prepared = PreparedSvg {
            source_name: "shape.svg".to_owned(),
            strokes: vec![SvgIrStroke::new(vec![
                SvgIrSegment::line(vec2(0.0, 0.0), vec2(10.0, 0.0)),
                SvgIrSegment::line(vec2(10.0, 0.0), vec2(20.0, 0.0)),
            ])],
            warnings: Vec::new(),
            drawing_origin: vec2(0.0, 0.0),
            drawing_bounds: vec2(20.0, 0.0),
            is_out_of_bounds: false,
        };

        let plan = build_plan(prepared, &ToolSettings::default());
        let draw_lines = plan
            .gcode_lines
            .iter()
            .filter(|line| line.starts_with("G1 X"))
            .cloned()
            .collect::<Vec<_>>();

        assert!(draw_lines.iter().any(|line| line.contains(" F")));
        assert!(draw_lines.iter().any(|line| !line.contains(" F")));
    }
}
