use glam::vec3;

use crate::{
    plot::model::{MotionKind, MotionSegment, ToolSettings, ToolpathPlan, ToolpathStats},
    svg::toolpath::PreparedSvg,
};

pub fn build_plan(prepared: PreparedSvg, settings: &ToolSettings) -> ToolpathPlan {
    let mut segments = Vec::new();
    let mut gcode_lines = Vec::new();

    let draw_feed = settings.print_feed_rate();
    let travel_feed = settings.travel_feed_rate();
    let lift = settings.lift_height_mm;

    gcode_lines.push("; Generated by Penartic".to_owned());
    gcode_lines.push(format!("; Source: {}", prepared.source_name));
    gcode_lines.push("G21".to_owned());
    gcode_lines.push("G90".to_owned());

    let mut current = vec3(0.0, 0.0, 0.0);
    let lifted_origin = vec3(0.0, 0.0, lift);
    if current.distance_squared(lifted_origin) > 1e-6 {
        segments.push(MotionSegment {
            start: current,
            end: lifted_origin,
            kind: MotionKind::Travel,
        });
        gcode_lines.push(format!("G1 Z{lift:.3} F{travel_feed:.0}"));
        current = lifted_origin;
    }

    gcode_lines.push("G28 X Y".to_owned());

    let mut stroke_count = 0;

    for polyline in prepared.polylines.iter().filter(|polyline| polyline.len() >= 2) {
        stroke_count += 1;

        let start = vec3(polyline[0].x, polyline[0].y, lift);
        if current.distance_squared(start) > 1e-6 {
            segments.push(MotionSegment { start: current, end: start, kind: MotionKind::Travel });
            gcode_lines.push(format!("G1 X{:.3} Y{:.3} F{travel_feed:.0}", start.x, start.y));
            current = start;
        }

        let lowered = vec3(start.x, start.y, 0.0);
        if current.distance_squared(lowered) > 1e-6 {
            segments.push(MotionSegment { start: current, end: lowered, kind: MotionKind::Travel });
            gcode_lines.push(format!("G1 Z{:.3} F{travel_feed:.0}", lowered.z));
            current = lowered;
        }

        for point in polyline.iter().skip(1) {
            let next = vec3(point.x, point.y, 0.0);
            if current.distance_squared(next) <= 1e-6 {
                continue;
            }

            segments.push(MotionSegment { start: current, end: next, kind: MotionKind::Draw });
            gcode_lines.push(format!("G1 X{:.3} Y{:.3} F{draw_feed:.0}", next.x, next.y));
            current = next;
        }

        let raised = vec3(current.x, current.y, lift);
        if current.distance_squared(raised) > 1e-6 {
            segments.push(MotionSegment { start: current, end: raised, kind: MotionKind::Travel });
            gcode_lines.push(format!("G1 Z{lift:.3} F{travel_feed:.0}"));
            current = raised;
        }
    }

    gcode_lines.push("M400".to_owned());

    let mut stats =
        ToolpathStats { stroke_count, segment_count: segments.len(), ..Default::default() };

    for segment in &segments {
        match segment.kind {
            MotionKind::Travel => {
                stats.travel_distance_mm += segment.length();
                stats.estimated_duration_s += segment.length() / (travel_feed / 60.0);
            }
            MotionKind::Draw => {
                stats.drawing_distance_mm += segment.length();
                stats.estimated_duration_s += segment.length() / (draw_feed / 60.0);
            }
        }
    }

    ToolpathPlan {
        source_name: prepared.source_name,
        printable_area: settings.printable_area,
        drawing_bounds: prepared.drawing_bounds,
        segments,
        gcode_lines,
        warnings: prepared.warnings,
        stats,
    }
}

#[cfg(test)]
mod tests {
    use glam::vec2;

    use super::*;
    use crate::plot::model::{PrintableArea, ToolSettings};
    use crate::svg::toolpath::PreparedSvg;

    #[test]
    fn generated_gcode_lifts_then_homes_xy() {
        let prepared = PreparedSvg {
            source_name: "shape.svg".to_owned(),
            polylines: vec![vec![vec2(10.0, 10.0), vec2(40.0, 10.0)]],
            warnings: Vec::new(),
            drawing_bounds: vec2(30.0, 0.0),
        };

        let plan = build_plan(
            prepared,
            &ToolSettings {
                printable_area: PrintableArea::new(100.0, 100.0),
                print_speed_mm_s: 25.0,
                lift_height_mm: 2.0,
            },
        );

        assert_eq!(plan.gcode_lines[2], "G21");
        assert_eq!(plan.gcode_lines[3], "G90");
        assert!(plan.gcode_lines[4].starts_with("G1 Z2.000"));
        assert_eq!(plan.gcode_lines[5], "G28 X Y");
    }
}
